version: '2.1'

services:
  client:
    image: client
    build: ./client
    volumes:
      - ./client:/clientapp
    environment:
      NODE_ENV: production
    ports:
      - 4200:4200
  server:
    image: server
    build: ./server
    volumes:
      - ./server:/serverapp
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000