version: '2.1'

services:
  client:
    image: client
    build: ./client
    volumes:
      - ./client:/usr/src/app/clientapp
    environment:
      NODE_ENV: development
    ports:
      - 4200:4200
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js
  server:
    image: server
    build: ./server
    volumes:
      - ./server:/usr/src/app/serverapp
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 app.js